use std::collections::{BTreeMap, HashMap, HashSet};
use std::fs;
use std::path::Path;

use anyhow::Result;
use chrono::Utc;

use crate::index::RuntimeIndex;

const MAX_ENTRY_POINTS: usize = 10;
const MAX_HOTSPOT_FILES: usize = 10;
const MAX_SYMBOLS: usize = 20;

pub fn generate_project_map(runtime: &RuntimeIndex) -> String {
    let chunks = runtime.all_chunks();

    // Count chunks per file (proxy for code density / centrality)
    let mut chunks_per_file: HashMap<&str, usize> = HashMap::new();
    for chunk in chunks {
        *chunks_per_file.entry(chunk.path.as_str()).or_insert(0) += 1;
    }

    // Entry points by basename heuristic
    let mut entry_points: Vec<&str> = chunks_per_file
        .keys()
        .copied()
        .filter(|path| is_entry_point(path))
        .collect();
    entry_points.sort();
    entry_points.truncate(MAX_ENTRY_POINTS);

    // Top files by chunk count
    let mut hotspots: Vec<(&str, usize)> = chunks_per_file
        .iter()
        .map(|(p, c)| (*p, *c))
        .collect();
    hotspots.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(b.0)));
    hotspots.truncate(MAX_HOTSPOT_FILES);

    // Top symbols from symbol_hint fields (deduplicated)
    let mut seen_symbols: HashSet<&str> = HashSet::new();
    let mut symbol_entries: Vec<(&str, &str, usize)> = Vec::new();
    for chunk in chunks {
        if let Some(sym) = &chunk.symbol_hint {
            let sym = sym.trim();
            if !sym.is_empty() && seen_symbols.insert(sym) {
                symbol_entries.push((sym, chunk.path.as_str(), chunk.start_line));
            }
        }
    }
    symbol_entries.truncate(MAX_SYMBOLS);

    // Directory overview (count unique files per top-level dir)
    let mut dir_file_counts: BTreeMap<String, usize> = BTreeMap::new();
    for path in chunks_per_file.keys() {
        let dir = top_dir(path);
        *dir_file_counts.entry(dir).or_insert(0) += 1;
    }

    let now = Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string();
    let mut out = format!("# Project Map (generated by budi)\nLast updated: {now}\n\n");

    out.push_str("## Entry Points\n");
    for path in &entry_points {
        out.push_str(&format!("- {path}\n"));
    }
    if entry_points.is_empty() {
        out.push_str("- (none detected)\n");
    }

    out.push_str("\n## Top Files by Code Density\n");
    for (i, (path, count)) in hotspots.iter().enumerate() {
        out.push_str(&format!("{}. {} ({} chunks)\n", i + 1, path, count));
    }

    out.push_str("\n## Top Symbols\n");
    for (sym, path, line) in &symbol_entries {
        out.push_str(&format!("- {sym} ({path}:{line})\n"));
    }

    out.push_str("\n## Directory Overview\n");
    for (dir, count) in &dir_file_counts {
        out.push_str(&format!("- {dir}/ ({count} files)\n"));
    }

    out
}

pub fn write_project_map(runtime: &RuntimeIndex, repo_root: &Path) -> Result<()> {
    let map = generate_project_map(runtime);
    let claude_dir = repo_root.join(".claude");
    fs::create_dir_all(&claude_dir)?;
    let map_path = claude_dir.join("budi-project-map.md");
    fs::write(map_path, map)?;
    Ok(())
}

pub fn read_project_map(repo_root: &Path) -> Option<String> {
    let map_path = repo_root.join(".claude").join("budi-project-map.md");
    fs::read_to_string(map_path).ok()
}

fn is_entry_point(path: &str) -> bool {
    let lower = path.to_ascii_lowercase();
    let stem = Path::new(&lower)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("");
    matches!(stem, "index" | "main" | "lib" | "mod" | "app" | "root")
}

fn top_dir(path: &str) -> String {
    path.split('/')
        .next()
        .filter(|s| !s.is_empty())
        .unwrap_or(".")
        .to_string()
}
