name: Feature request
description: Suggest an improvement or new feature
title: "feat: "
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: Describe the problem you're trying to solve and/or the feature you'd like to see.
    validations:
      required: true
