# typed: false
# frozen_string_literal: true

# This formula is auto-generated by the release workflow.
# Do not edit manually — changes will be overwritten.

class Budi < Formula
  desc "Local-first cost analytics for AI coding agents"
  homepage "https://github.com/siropkin/budi"
  version "{{VERSION}}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/siropkin/budi/releases/download/v{{VERSION}}/budi-v{{VERSION}}-aarch64-apple-darwin.tar.gz"
      sha256 "{{SHA256_AARCH64_DARWIN}}"
    else
      url "https://github.com/siropkin/budi/releases/download/v{{VERSION}}/budi-v{{VERSION}}-x86_64-apple-darwin.tar.gz"
      sha256 "{{SHA256_X86_64_DARWIN}}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/siropkin/budi/releases/download/v{{VERSION}}/budi-v{{VERSION}}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "{{SHA256_AARCH64_LINUX}}"
    else
      url "https://github.com/siropkin/budi/releases/download/v{{VERSION}}/budi-v{{VERSION}}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "{{SHA256_X86_64_LINUX}}"
    end
  end

  def install
    bin.install "budi"
    bin.install "budi-daemon"
  end

  def caveats
    <<~EOS
      Get started:
        budi init

      Restart Claude Code and Cursor to activate hooks and the status line.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/budi --version")
  end
end
