#!/usr/bin/env python3
"""Fine-tune ms-marco-MiniLM-L-6-v2 cross-encoder on budi's code retrieval data.

Uses sentence-transformers CrossEncoder with training data generated by
reranker_training_data.py. Produces a PyTorch model that can be exported to ONNX.

Usage:
    # Activate venv first
    source scripts/dev/reranker-venv/bin/activate
    python3 scripts/dev/reranker_finetune.py [--epochs 5] [--batch-size 16]
"""

import argparse
import json
import math
import random
from pathlib import Path

import torch
from sentence_transformers import InputExample
from sentence_transformers.cross_encoder import CrossEncoder
from sentence_transformers.cross_encoder.evaluation import (
    CEBinaryClassificationEvaluator,
)
from torch.utils.data import DataLoader


def load_training_data(path: str) -> list[dict]:
    """Load JSONL training data."""
    pairs = []
    with open(path) as f:
        for line in f:
            pairs.append(json.loads(line))
    return pairs


def split_data(
    pairs: list[dict], val_ratio: float = 0.15, seed: int = 42
) -> tuple[list[dict], list[dict]]:
    """Split data into train/val, stratified by repo to avoid data leakage."""
    random.seed(seed)

    # Group by repo
    by_repo: dict[str, list[dict]] = {}
    for p in pairs:
        by_repo.setdefault(p["repo"], []).append(p)

    train, val = [], []
    for repo, items in by_repo.items():
        random.shuffle(items)
        n_val = max(1, int(len(items) * val_ratio))
        val.extend(items[:n_val])
        train.extend(items[n_val:])

    random.shuffle(train)
    random.shuffle(val)
    return train, val


def to_input_examples(pairs: list[dict]) -> list[InputExample]:
    """Convert to sentence-transformers format."""
    return [
        InputExample(texts=[p["query"], p["passage"]], label=p["label"])
        for p in pairs
    ]


def main():
    parser = argparse.ArgumentParser(description="Fine-tune reranker cross-encoder")
    parser.add_argument(
        "--data",
        default="scripts/dev/reranker_training_data.jsonl",
        help="Training data JSONL",
    )
    parser.add_argument("--epochs", type=int, default=5, help="Training epochs")
    parser.add_argument("--batch-size", type=int, default=16, help="Batch size")
    parser.add_argument(
        "--lr", type=float, default=2e-5, help="Learning rate"
    )
    parser.add_argument(
        "--warmup-ratio", type=float, default=0.1, help="Warmup ratio"
    )
    parser.add_argument(
        "--output-dir",
        default="scripts/dev/reranker-finetuned",
        help="Output directory for the fine-tuned model",
    )
    parser.add_argument(
        "--base-model",
        default="cross-encoder/ms-marco-MiniLM-L-6-v2",
        help="Base model to fine-tune",
    )
    args = parser.parse_args()

    print(f"Loading training data from {args.data}...")
    pairs = load_training_data(args.data)
    print(f"Loaded {len(pairs)} pairs")

    # Split
    train_pairs, val_pairs = split_data(pairs)
    print(f"Train: {len(train_pairs)}, Val: {len(val_pairs)}")

    # Convert
    train_examples = to_input_examples(train_pairs)
    val_examples = to_input_examples(val_pairs)

    # Stats
    train_pos = sum(1 for p in train_pairs if p["label"] > 0.5)
    train_neg = sum(1 for p in train_pairs if p["label"] <= 0.5)
    val_pos = sum(1 for p in val_pairs if p["label"] > 0.5)
    val_neg = sum(1 for p in val_pairs if p["label"] <= 0.5)
    print(f"Train: {train_pos} pos, {train_neg} neg")
    print(f"Val: {val_pos} pos, {val_neg} neg")

    # Initialize cross-encoder
    print(f"\nLoading base model: {args.base_model}")
    model = CrossEncoder(
        args.base_model,
        num_labels=1,
        max_length=512,
    )

    # Evaluate BEFORE training (baseline)
    print("\n--- Baseline evaluation (before fine-tuning) ---")
    evaluator = CEBinaryClassificationEvaluator.from_input_examples(
        val_examples, name="val"
    )
    baseline_result = evaluator(model, output_path=None)
    # evaluator returns a dict or float depending on version
    if isinstance(baseline_result, dict):
        baseline_score = baseline_result.get("val_average_precision", baseline_result.get("val_ap", list(baseline_result.values())[0]))
        print(f"Baseline eval: {baseline_result}")
    else:
        baseline_score = baseline_result
    print(f"Baseline val score: {baseline_score:.4f}")

    # Score a few examples to show the problem
    print("\nSample scores BEFORE fine-tuning:")
    sample = random.sample(pairs, min(5, len(pairs)))
    for p in sample:
        score = model.predict([(p["query"], p["passage"])])[0]
        print(
            f"  label={p['label']:.1f} score={score:.4f} | "
            f"{p['intent']} | {p['path'][:40]}"
        )

    # Training
    train_dataloader = DataLoader(
        train_examples, shuffle=True, batch_size=args.batch_size
    )
    warmup_steps = math.ceil(
        len(train_dataloader) * args.epochs * args.warmup_ratio
    )

    print(f"\n--- Training ---")
    print(f"Epochs: {args.epochs}")
    print(f"Batch size: {args.batch_size}")
    print(f"Learning rate: {args.lr}")
    print(f"Warmup steps: {warmup_steps}")
    print(f"Total steps: {len(train_dataloader) * args.epochs}")

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    model.fit(
        train_dataloader=train_dataloader,
        evaluator=evaluator,
        epochs=args.epochs,
        warmup_steps=warmup_steps,
        optimizer_params={"lr": args.lr},
        output_path=str(output_dir),
        save_best_model=True,
        show_progress_bar=True,
    )

    # Explicitly save the model
    model.save(str(output_dir))
    print(f"Model saved to {output_dir}")

    # Evaluate AFTER training
    print("\n--- Post-training evaluation ---")
    final_result = evaluator(model, output_path=None)
    if isinstance(final_result, dict):
        final_score = final_result.get("val_average_precision", final_result.get("val_ap", list(final_result.values())[0]))
        print(f"Final eval: {final_result}")
    else:
        final_score = final_result
    print(f"Final val score: {final_score:.4f} (baseline: {baseline_score:.4f})")
    print(f"Improvement: {final_score - baseline_score:+.4f}")

    # Score the same samples after fine-tuning
    print("\nSample scores AFTER fine-tuning:")
    for p in sample:
        score = model.predict([(p["query"], p["passage"])])[0]
        print(
            f"  label={p['label']:.1f} score={score:.4f} | "
            f"{p['intent']} | {p['path'][:40]}"
        )

    # Save model info
    info = {
        "base_model": args.base_model,
        "epochs": args.epochs,
        "batch_size": args.batch_size,
        "lr": args.lr,
        "train_size": len(train_pairs),
        "val_size": len(val_pairs),
        "baseline_score": float(baseline_score),
        "final_score": float(final_score),
    }
    with open(output_dir / "training_info.json", "w") as f:
        json.dump(info, f, indent=2)

    print(f"\nModel saved to {output_dir}")
    print("Next step: python3 scripts/dev/reranker_export_onnx.py")


if __name__ == "__main__":
    main()
