//! `budi cloud` subcommands — manual cloud sync and freshness reporting.
//!
//! 8.1 R2.1 (issue #225) introduces `budi cloud sync` as the user-facing way
//! to say "push my latest local data to cloud now" without waiting for the
//! background worker interval (ADR-0083 §9). `budi cloud status` shows the
//! same readiness snapshot the daemon exposes at `GET /cloud/status` so users
//! can answer "is cloud sync healthy?" without reading logs. 8.3 R F (issue
//! #446) adds `budi cloud init` so a fresh user never has to hand-write the
//! `cloud.toml` schema.
//!
//! Both commands follow the normalized CLI output contract shared with
//! `budi stats` / `budi sessions`:
//! - `--format text` is the default, human-readable with ✓/✗ status lines.
//! - `--format json` emits the daemon response body verbatim for scripting.

use std::fs;
use std::io::{self, IsTerminal, Write};

use anyhow::{Context, Result, anyhow};
use budi_core::config::{CLOUD_API_KEY_STUB, cloud_config_path, load_cloud_config};
use serde_json::Value;

use crate::StatsFormat;
use crate::client::DaemonClient;

use super::ansi;

/// `budi cloud init` — generate a commented `~/.config/budi/cloud.toml`
/// template so a fresh user never has to hand-write the schema from
/// ADR-0083 §9. If `api_key` is `Some`, the template is written with
/// `enabled = true` and the real key in place; otherwise a stub key
/// (`CLOUD_API_KEY_STUB`) is written so the user can open the file and
/// paste their real key.
pub fn cmd_cloud_init(api_key: Option<String>, force: bool, yes: bool) -> Result<()> {
    let path = cloud_config_path().context("failed to resolve ~/.config/budi/cloud.toml path")?;

    let existed = path.exists();
    if existed {
        if !force {
            return Err(anyhow!(
                "{} already exists. Pass --force to overwrite (existing settings will be replaced).",
                path.display()
            ));
        }
        // `--force` overwrite: if the current api_key looks real, require
        // --yes or an interactive confirmation so a stray invocation doesn't
        // silently clobber a working config. Stub keys / no keys overwrite
        // freely because the prior install was never going to sync.
        let existing = load_cloud_config();
        let has_real_key = existing
            .api_key
            .as_deref()
            .map(|k| !k.is_empty() && k != CLOUD_API_KEY_STUB)
            .unwrap_or(false);
        if has_real_key && !yes && !confirm_overwrite(&path)? {
            println!("Aborted. {} left unchanged.", path.display());
            return Ok(());
        }
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }

    let (key_value, enabled) = match api_key.as_deref().map(str::trim) {
        Some(k) if !k.is_empty() => (k.to_string(), true),
        _ => (CLOUD_API_KEY_STUB.to_string(), false),
    };
    let rendered = render_cloud_toml_template(&key_value, enabled);
    fs::write(&path, rendered).with_context(|| format!("failed to write {}", path.display()))?;

    render_init_text(&path, existed, enabled);
    Ok(())
}

/// Build the on-disk template text. Kept pure and public-to-crate so the
/// unit tests can pin the shape without going through the filesystem.
fn render_cloud_toml_template(api_key: &str, enabled: bool) -> String {
    // Heavily commented so a user reading the file understands every field
    // without cross-referencing ADR-0083. Keep lines <= 78 cols so a
    // standard terminal pager doesn't wrap.
    let enabled_line = if enabled { "true" } else { "false" };
    let today = chrono::Utc::now().format("%Y-%m-%d");
    format!(
        "\
# budi cloud sync configuration (ADR-0083 §9)
# Generated by `budi cloud init` on {today}.
# Cloud sync is off by default. See https://app.getbudi.dev for an account.

[cloud]
# Flip to `true` after pasting a real api_key below. `budi cloud sync` is
# a no-op while `enabled = false` or while api_key is the placeholder.
enabled = {enabled_line}

# Paste your API key from Settings → API keys at https://app.getbudi.dev.
# `budi cloud status` will report \"disabled (stub key)\" while this still
# reads `PASTE_YOUR_KEY_HERE`, so you can tell at a glance whether this
# step is done.
api_key = \"{api_key}\"

# Endpoint for the cloud API. Leave the default unless you are testing a
# self-hosted ingester.
endpoint = \"https://app.getbudi.dev\"

# Optional. Only prompts, code, and responses are stripped before upload —
# these two fields identify which device and workspace the daily rollups
# belong to on the dashboard. `budi init` seeds them automatically on a
# real enable, but you can set them explicitly for multi-machine setups.
# device_id = \"your-device-id\"
# org_id = \"your-org-id\"

[cloud.sync]
# Background sync interval in seconds. Defaults to 300 (5 minutes).
interval_seconds = 300
# Upper bound on retry backoff in seconds. Defaults to 300.
retry_max_seconds = 300
"
    )
}

fn confirm_overwrite(path: &std::path::Path) -> Result<bool> {
    // We print to stdout rather than stderr so piped consumers that
    // dropped stdin still see the prompt line alongside the aborted
    // message. If stdin is not a TTY, treat the answer as "no" so an
    // automated invocation without `--yes` never silently destroys a
    // working config.
    if !io::stdin().is_terminal() {
        return Ok(false);
    }
    print!(
        "{} already exists with a non-stub api_key. Overwrite? [y/N] ",
        path.display()
    );
    io::stdout().flush().ok();
    let mut answer = String::new();
    if io::stdin().read_line(&mut answer).is_err() {
        return Ok(false);
    }
    Ok(matches!(
        answer.trim().to_ascii_lowercase().as_str(),
        "y" | "yes"
    ))
}

fn render_init_text(path: &std::path::Path, existed: bool, enabled: bool) {
    let green = ansi("\x1b[32m");
    let dim = ansi("\x1b[90m");
    let bold = ansi("\x1b[1m");
    let reset = ansi("\x1b[0m");

    let verb = if existed { "Overwrote" } else { "Created" };
    println!();
    println!(
        "  {green}✓{reset} {bold}{verb} cloud config template:{reset} {}",
        path.display()
    );
    println!();
    if enabled {
        println!("  {bold}Next steps{reset}");
        println!("    1. {dim}Restart the daemon:{reset} budi init");
        println!(
            "    2. {dim}Confirm:{reset}            budi cloud status   (expect 'state: ready')"
        );
        println!("    3. {dim}Push now:{reset}           budi cloud sync");
    } else {
        println!("  {bold}Next steps{reset}");
        println!("    1. {dim}Sign up:{reset}  open https://app.getbudi.dev");
        println!(
            "    2. {dim}Paste key:{reset} replace `PASTE_YOUR_KEY_HERE` in {}",
            path.display()
        );
        println!("    3. {dim}Enable:{reset}   set `enabled = true` in the same file");
        println!("    4. {dim}Restart:{reset}  budi init");
        println!("    5. {dim}Confirm:{reset}  budi cloud status");
        println!("    6. {dim}Push now:{reset} budi cloud sync");
    }
    println!();
}

/// `budi cloud sync` — flush the pending cloud queue now.
pub fn cmd_cloud_sync(format: StatsFormat) -> Result<()> {
    let client = DaemonClient::connect()?;
    let body = client.cloud_sync()?;

    if matches!(format, StatsFormat::Json) {
        super::print_json(&body)?;
        // Exit non-zero on non-ok result so scripts can branch on status.
        if body.get("ok").and_then(Value::as_bool) != Some(true) {
            std::process::exit(2);
        }
        return Ok(());
    }

    render_sync_text(&body);
    if body.get("ok").and_then(Value::as_bool) != Some(true) {
        std::process::exit(2);
    }
    Ok(())
}

/// `budi cloud status` — report cloud sync readiness and last-synced-at.
pub fn cmd_cloud_status(format: StatsFormat) -> Result<()> {
    let client = DaemonClient::connect()?;
    let body = client.cloud_status()?;

    if matches!(format, StatsFormat::Json) {
        super::print_json(&body)?;
        return Ok(());
    }

    render_status_text(&body);
    Ok(())
}

fn render_sync_text(body: &Value) {
    let green = ansi("\x1b[32m");
    let red = ansi("\x1b[31m");
    let yellow = ansi("\x1b[33m");
    let dim = ansi("\x1b[90m");
    let bold = ansi("\x1b[1m");
    let reset = ansi("\x1b[0m");

    let ok = body.get("ok").and_then(Value::as_bool).unwrap_or(false);
    let result = body
        .get("result")
        .and_then(Value::as_str)
        .unwrap_or("unknown");
    let message = body.get("message").and_then(Value::as_str).unwrap_or("");
    let endpoint = body.get("endpoint").and_then(Value::as_str).unwrap_or("");
    let records = body
        .get("records_upserted")
        .and_then(Value::as_i64)
        .unwrap_or(0);
    let rollups = body
        .get("rollups_attempted")
        .and_then(Value::as_i64)
        .unwrap_or(0);
    let sessions = body
        .get("sessions_attempted")
        .and_then(Value::as_i64)
        .unwrap_or(0);
    let watermark = body.get("watermark").and_then(Value::as_str);

    println!();
    let (icon, color, headline) = match (ok, result) {
        (true, "success") => (
            "✓",
            green,
            format!("Cloud sync complete ({records} records pushed)"),
        ),
        (true, "empty_payload") => ("✓", green, "Nothing new to sync".to_string()),
        (_, "disabled") => ("-", dim, "Cloud sync is disabled".to_string()),
        (_, "not_configured") => ("!", yellow, "Cloud sync is not configured".to_string()),
        (_, "auth_failure") => ("✗", red, "Cloud sync failed: authentication".to_string()),
        (_, "schema_mismatch") => ("✗", red, "Cloud sync failed: schema mismatch".to_string()),
        (_, "transient_error") => ("✗", red, "Cloud sync failed: transient error".to_string()),
        _ => ("✗", red, format!("Cloud sync result: {result}")),
    };

    println!("  {color}{icon}{reset} {bold}{headline}{reset}");
    if !message.is_empty() {
        println!("    {dim}{message}{reset}");
    }
    if !endpoint.is_empty() {
        println!("    {dim}endpoint{reset}   {endpoint}");
    }
    if rollups > 0 || sessions > 0 {
        println!("    {dim}attempted{reset}  {rollups} rollups, {sessions} sessions");
    }
    if let Some(wm) = watermark {
        println!("    {dim}watermark{reset}  {wm}");
    }
    println!();
}

fn render_status_text(body: &Value) {
    let green = ansi("\x1b[32m");
    let red = ansi("\x1b[31m");
    let yellow = ansi("\x1b[33m");
    let dim = ansi("\x1b[90m");
    let bold_cyan = ansi("\x1b[1;36m");
    let bold = ansi("\x1b[1m");
    let reset = ansi("\x1b[0m");

    let enabled = body
        .get("enabled")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    let configured = body
        .get("configured")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    let ready = body.get("ready").and_then(Value::as_bool).unwrap_or(false);
    // Older daemons don't emit these fields; treat them as false so the
    // pre-#446 "disabled" branch still fires instead of the new "no config"
    // branch when a new CLI talks to an old daemon.
    let config_exists = body
        .get("config_exists")
        .and_then(Value::as_bool)
        .unwrap_or(true);
    let api_key_stub = body
        .get("api_key_stub")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    let endpoint = body.get("endpoint").and_then(Value::as_str).unwrap_or("");
    let last_synced_at = body.get("last_synced_at").and_then(Value::as_str);
    let watermark = body.get("rollup_watermark").and_then(Value::as_str);
    let pending_rollups = body
        .get("pending_rollups")
        .and_then(Value::as_i64)
        .unwrap_or(0);
    let pending_sessions = body
        .get("pending_sessions")
        .and_then(Value::as_i64)
        .unwrap_or(0);

    println!();
    println!("  {bold_cyan} budi cloud status{reset}");
    println!("  {dim}{}{reset}", "─".repeat(40));

    // Order matters: "ready" dominates; otherwise we pick the most specific
    // not-ready label so the next-step hint under the panel can point at the
    // exact thing that is missing (#446).
    let (state_icon, state_color, state_label) = if ready {
        ("✓", green, "ready")
    } else if !config_exists {
        ("-", dim, "disabled (no config)")
    } else if api_key_stub {
        ("!", yellow, "disabled (stub key)")
    } else if enabled && !configured {
        ("!", yellow, "enabled but missing api_key")
    } else if enabled {
        ("!", yellow, "enabled but not fully configured")
    } else {
        ("-", dim, "disabled")
    };
    println!(
        "  {state_color}{state_icon}{reset} {bold}State{reset}      {state_color}{state_label}{reset}"
    );

    if !endpoint.is_empty() {
        println!("    {dim}endpoint{reset}   {endpoint}");
    }

    match last_synced_at {
        Some(ts) => println!("    {dim}last sync{reset}  {ts}"),
        None => println!("    {dim}last sync{reset}  {red}never{reset}"),
    }
    if let Some(wm) = watermark {
        println!("    {dim}watermark{reset}  {wm}");
    }
    if pending_rollups > 0 || pending_sessions > 0 {
        println!(
            "    {dim}pending{reset}    {yellow}{pending_rollups} rollups, {pending_sessions} sessions{reset}  (run `budi cloud sync`)"
        );
    }

    if !ready {
        println!();
        if !config_exists {
            println!(
                "  {dim}No ~/.config/budi/cloud.toml yet. Run{reset} {bold}budi cloud init{reset} {dim}to generate a template.{reset}"
            );
        } else if api_key_stub {
            println!(
                "  {yellow}API key not set —{reset} paste your key from https://app.getbudi.dev into ~/.config/budi/cloud.toml, then set `enabled = true`."
            );
        } else if !enabled {
            println!(
                "  {dim}Cloud sync is off. Enable it by setting `enabled = true` in{reset} ~/.config/budi/cloud.toml"
            );
        } else if !configured {
            println!(
                "  {yellow}Cloud sync is enabled but missing credentials.{reset} See ~/.config/budi/cloud.toml"
            );
        }
    }
    println!();
}

#[cfg(test)]
mod tests {
    use super::*;
    use budi_core::config::CloudConfig;

    #[test]
    fn template_stub_variant_is_disabled_and_carries_placeholder() {
        let out = render_cloud_toml_template(CLOUD_API_KEY_STUB, false);
        assert!(out.contains("enabled = false"));
        assert!(out.contains("PASTE_YOUR_KEY_HERE"));
        assert!(
            out.contains("[cloud]"),
            "top-level section must match ADR-0083 §9 wire shape"
        );
        assert!(
            out.contains("[cloud.sync]"),
            "sync tuning block must be present so interval/retry are discoverable"
        );
    }

    #[test]
    fn template_with_real_key_is_enabled() {
        let out = render_cloud_toml_template("fake-test-key", true);
        assert!(out.contains("enabled = true"));
        assert!(out.contains("api_key = \"fake-test-key\""));
        // The comment above `api_key = ...` legitimately references the
        // placeholder string so users recognize the "stub key" status line —
        // assert on the actual assignment instead of a global search so we
        // pin the behaviour that matters (no live key written with the stub
        // value) without being precious about the inline docstring.
        assert!(
            !out.contains("api_key = \"PASTE_YOUR_KEY_HERE\""),
            "real-key path must not emit an api_key assignment of the stub value"
        );
    }

    #[test]
    fn template_is_valid_toml_and_round_trips_through_cloud_config() {
        let out = render_cloud_toml_template("fake-test-key", true);
        // The generated file uses a top-level [cloud] section, so parse it
        // via a small wrapper that mirrors `load_cloud_config`'s contract.
        #[derive(serde::Deserialize)]
        struct Wrapper {
            cloud: CloudConfig,
        }
        let w: Wrapper = toml::from_str(&out).expect("generated template must be valid TOML");
        assert!(w.cloud.enabled);
        assert_eq!(w.cloud.api_key.as_deref(), Some("fake-test-key"));
        assert_eq!(w.cloud.endpoint, "https://app.getbudi.dev");
        assert_eq!(w.cloud.sync.interval_seconds, 300);
    }

    #[test]
    fn template_stub_round_trips_as_stub() {
        let out = render_cloud_toml_template(CLOUD_API_KEY_STUB, false);
        #[derive(serde::Deserialize)]
        struct Wrapper {
            cloud: CloudConfig,
        }
        let w: Wrapper = toml::from_str(&out).unwrap();
        assert!(!w.cloud.enabled);
        assert!(w.cloud.is_api_key_stub());
    }
}
